version: '1'
services:

  mysql:
    container_name: some-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: customer
      MYSQL_ROOT_PASSWORD: mahran1998
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  app:
    container_name: app
    image: mahran1998/app:1.2
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
